name: Make release

on:
  release:
    types: [created]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project
      uses: actions/checkout@v4
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23.2'
    - name: Build files
      run: |
        CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -ldflags '-extldflags "-static" -X "main.Version=${{ github.event.release.name }}"' -o torrenter_windows_amd64
        CGO_ENABLED=0 GOOS=linux GOARCH=arm go build -ldflags '-extldflags "-static" -X "main.Version=${{ github.event.release.name }}"' -o torrenter_linux_arm
        CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -ldflags '-extldflags "-static" -X "main.Version=${{ github.event.release.name }}"' -o torrenter_linux_arm64
        CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags '-extldflags "-static" -X "main.Version=${{ github.event.release.name }}"' -o torrenter_linux_amd64
        ./torrenter_linux_amd64 --version
    - name: Create checksums.txt
      run: |
        touch torrenter_${{ github.event.release.name }}_checksums.txt
        sha256sum torrenter_windows_amd64 >> torrenter_${{ github.event.release.name }}_checksums.txt
        sha256sum torrenter_linux_arm >> torrenter_${{ github.event.release.name }}_checksums.txt
        sha256sum torrenter_linux_arm64 >> torrenter_${{ github.event.release.name }}_checksums.txt
        sha256sum torrenter_linux_amd64 >> torrenter_${{ github.event.release.name }}_checksums.txt
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          torrenter_${{ github.event.release.name }}_checksums.txt
          torrenter_windows_amd64
          torrenter_linux_arm
          torrenter_linux_arm64
          torrenter_linux_amd64
          
