name: Make release

on:
  release:
    types: [created]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project
      uses: actions/checkout@v4
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.4'
    - name: Build files
      run: |
        CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags '-extldflags "-static"' -o torrenter_linux_amd64
    - name: Create checksums.txt
      run: |
        touch torrenter_${{ github.event.release.name }}_checksums.txt
        sha256sum torrenter_linux_amd64 >> torrenter_${{ github.event.release.name }}_checksums.txt
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          torrenter_${{ github.event.release.name }}_checksums.txt
          torrenter_linux_amd64